# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'PromptKit' do
pod 'ReactiveCocoa'
pod 'MJRefresh'
pod 'AFNetworking'
pod 'MBProgressHUD', '~> 1.0.0'
end

target 'PromptKitTests' do

end

